
name: intro-to-holoviz
channels:
  - conda-forge
dependencies:
  - bokeh
  - geoviews
  - hvplot
  - ipywidgets
  - jupyterlab>=3
  - matplotlib
  - netcdf4
  - pandas
  - panel
  - pooch
  - python=3.9
  - xarray
